name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t brightstraining24fall.azurecr.io/mycontainer:latest ./webapi/java

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: brightstraining24fall.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        run: docker push brightstraining24fall.azurecr.io/mycontainer:latest


 
