name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # Install Java from Eclipse Temurin
          java-version: '17'

      - name: Build Docker Image
        run: docker build -t brightstraining24fall.azurecr.io/mycontainer:latest ./webapi/java

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: brightstraining24fall.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and deploy Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: myApp
          resourceGroup: rg_Fredrik-test-01
          imageToDeploy: brightstraining24fall.azurecr.io/mycontainer:latest
          acrName: brhitgstrainingfall24
          containerAppEnvironment: env-fredrik-01
          acrUsername: ${{ secrets.DOCKER_USERNAME }}
          acrPassword: ${{ secrets.DOCKER_PASSWORD }}
          location: "norway east"

      - name: Push Image
        run: docker push brightstraining24fall.azurecr.io/mycontainer:latest

      - name: Run Tests
        working-directory: ./webapi/java
        run: mvn test


 
