name: Hello World Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: brightstraining24fall.azurecr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with: 
          context: ./brights-webapi/java/src
          push: true
          tags: |
            brightstraining24fall.azurecr.io/fredrik/mycontainer:latest
            brightstraining24fall.azurecr.io/fredrik/mycontainer:${{ github.sha }}

      - name: Hello World Step
        run: echo "Hello, World! Build pipeline is running."
 
